name: Deploy production

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: yarn install
      - run: npx browserslist@latest --update-db
      - run: yarn build

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: ./build/*
          scp_target: /usr/share/nginx/evopayment-tochka/
          before_script: |
            rm -rf /usr/share/nginx/evopayment-tochka/*
